## BWA alignment against Hg30 (filtered reads containing CMV primer sequence)

In [17]:
# -- Create directories for references/aligments (RUN JUST ONCE)
from pathlib import Path

# -- Create directories for references/alignments
path = Path('/Users/leandro/Desktop/github/NGS-data/ORF2library1_260411/alignments/BWA/over-hg38')

In [ ]:
# Reads pre-preprocessing (search PCR primer sequence in R1 reads)
!fqgrep "CTCCATATATGGGCTATGAACTAATGACCCC" E3-control_S1_L001_R1_001.fastq.gz > matched_reads_E3.fastq
# same for other R1 files (done in terminal)

In [3]:
# Define data location

reads_dir = path/'merged'
fastq_files = sorted(reads_dir.glob("*.merged.fastq.gz"))

fastq_files

[PosixPath('/Users/leandro/Desktop/github/NGS-data/ORF2library1_260411/merged/E3-control_S1_L001.merged.fastq.gz'),
 PosixPath('/Users/leandro/Desktop/github/NGS-data/ORF2library1_260411/merged/Hs-sorted_S2_L001.merged.fastq.gz'),
 PosixPath('/Users/leandro/Desktop/github/NGS-data/ORF2library1_260411/merged/Rr-sorted_S3_L001.merged.fastq.gz')]

In [18]:
# Basic mapping statistics

for bam in path.glob("*.bam"):
    print(f"\n===== {bam.name} =====")
    !samtools flagstat {bam}

===== Rr.bam =====
402194 + 0 in total (QC-passed reads + QC-failed reads)
382203 + 0 primary
0 + 0 secondary
19991 + 0 supplementary
0 + 0 duplicates
0 + 0 primary duplicates
304242 + 0 mapped (75.65% : N/A)
284251 + 0 primary mapped (74.37% : N/A)
0 + 0 paired in sequencing
0 + 0 read1
0 + 0 read2
0 + 0 properly paired (N/A : N/A)
0 + 0 with itself and mate mapped
0 + 0 singletons (N/A : N/A)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)

===== Hs.bam =====
194790 + 0 in total (QC-passed reads + QC-failed reads)
185114 + 0 primary
0 + 0 secondary
9676 + 0 supplementary
0 + 0 duplicates
0 + 0 primary duplicates
154550 + 0 mapped (79.34% : N/A)
144874 + 0 primary mapped (78.26% : N/A)
0 + 0 paired in sequencing
0 + 0 read1
0 + 0 read2
0 + 0 properly paired (N/A : N/A)
0 + 0 with itself and mate mapped
0 + 0 singletons (N/A : N/A)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)

===== E3.bam =====
97490 + 0 in total (QC-passed reads + QC-failed reads)
92673 + 0 primary
0 + 0 secondary
4817 + 0 supplementary
0 + 0 duplicates
0 + 0 primary duplicates
82995 + 0 mapped (85.13% : N/A)
78178 + 0 primary mapped (84.36% : N/A)
0 + 0 paired in sequencing
0 + 0 read1
0 + 0 read2
0 + 0 properly paired (N/A : N/A)
0 + 0 with itself and mate mapped
0 + 0 singletons (N/A : N/A)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)

In [9]:
# Count uniquely mapped reads (MAPQ >0)

for bam in alignments.glob("*.bam"):
    print(f"\n===== {bam.name} =====")
    !samtools view -q 1 -c {bam}

===== Hs-sorted_S2_L001.hg38.bam =====
125906

python(82435) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

===== E3-control_S1_L001.hg38.bam =====
233944

python(82440) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

===== Rr-sorted_S3_L001.hg38.bam =====
231105

python(82441) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

In [19]:
# Number of distinct genomic loci hit

import subprocess

for bam in path.glob("*.bam"):
    print(f"\n===== {bam.name} =====")
    cmd = f"samtools view {bam} | awk '{{print $3\":\"$4}}' | sort | uniq | wc -l"
    subprocess.run(cmd, shell=True)

===== Rr.bam =====
  248970

===== Hs.bam =====
  133682

===== E3.bam =====
   70834

In [20]:
# Reads per chromosome

for bam in path.glob("*.bam"):
    print(f"\n===== {bam.name} =====")
    !samtools view {bam} | cut -f3 | sort | uniq -c

===== Rr.bam =====
97952 *
31886 1
15794 10
13960 11
11604 12
6848 13
8696 14
8744 15
11687 16
14553 17
5500 18
11934 19
20379 2
7919 20
5104 21
8762 22
17044 3
12096 4
14415 5
14988 6
15019 7
11530 8
11816 9
  22 GL000008.2
  38 GL000009.2
  62 GL000194.1
  15 GL000195.1
  60 GL000205.2
   5 GL000208.1
   5 GL000213.1
 682 GL000214.1
1262 GL000216.2
  22 GL000218.1
  20 GL000219.1
 120 GL000220.1
  19 GL000221.1
 114 GL000224.1
2494 GL000225.1
   5 KI270303.1
   7 KI270330.1
   1 KI270435.1
   4 KI270438.1
  47 KI270442.1
   1 KI270467.1
   7 KI270508.1
   5 KI270512.1
   8 KI270519.1
   1 KI270521.1
   6 KI270538.1
   2 KI270581.1
   1 KI270582.1
  29 KI270706.1
   9 KI270707.1
  17 KI270708.1
  25 KI270709.1
   1 KI270710.1
  17 KI270711.1
  36 KI270712.1
  21 KI270713.1
  22 KI270714.1
   1 KI270717.1
  18 KI270719.1
   1 KI270720.1
  29 KI270721.1
  22 KI270722.1
  28 KI270723.1
  28 KI270724.1
   9 KI270725.1
   3 KI270726.1
  16 KI270727.1
  98 KI270728.1
  34 KI270729.1
   2 KI270730.1
  47 KI270731.1
   6 KI270732.1
 111 KI270733.1
  36 KI270734.1
   5 KI270735.1
  17 KI270736.1
   4 KI270737.1
  10 KI270738.1
   2 KI270739.1
   3 KI270741.1
  22 KI270742.1
  50 KI270743.1
1571 KI270744.1
   7 KI270745.1
   2 KI270746.1
  12 KI270747.1
   7 KI270748.1
  14 KI270749.1
  11 KI270750.1
 485 KI270751.1
  35 KI270753.1
 181 KI270754.1
   2 KI270755.1
   1 KI270756.1
   1 KI270757.1
2220 MT
12639 X
 962 Y

===== Hs.bam =====
40240 *
16016 1
8021 10
6991 11
5847 12
3628 13
4296 14
4415 15
5890 16
6974 17
2765 18
5828 19
10317 2
4001 20
2512 21
4317 22
8619 3
6400 4
7316 5
7511 6
7741 7
5996 8
6093 9
  17 GL000008.2
  15 GL000009.2
  25 GL000194.1
  13 GL000195.1
  29 GL000205.2
   2 GL000208.1
   1 GL000213.1
 368 GL000214.1
 765 GL000216.2
  12 GL000218.1
   1 GL000219.1
  66 GL000220.1
  16 GL000221.1
  64 GL000224.1
1509 GL000225.1
   1 KI270310.1
   3 KI270330.1
   1 KI270435.1
   2 KI270438.1
  22 KI270442.1
   1 KI270508.1
   1 KI270512.1
   4 KI270519.1
   4 KI270538.1
   1 KI270539.1
   1 KI270581.1
   1 KI270584.1
  16 KI270706.1
   8 KI270707.1
   8 KI270708.1
  12 KI270709.1
   8 KI270711.1
  18 KI270712.1
   9 KI270713.1
  13 KI270714.1
   2 KI270717.1
   8 KI270719.1
   1 KI270720.1
  20 KI270721.1
   9 KI270722.1
  18 KI270723.1
  18 KI270724.1
   7 KI270725.1
  10 KI270727.1
  44 KI270728.1
  20 KI270729.1
   3 KI270730.1
  17 KI270731.1
   5 KI270732.1
  46 KI270733.1
  19 KI270734.1
   1 KI270735.1
   9 KI270736.1
   1 KI270737.1
   3 KI270738.1
   1 KI270741.1
   8 KI270742.1
  32 KI270743.1
 836 KI270744.1
   3 KI270745.1
   3 KI270746.1
   3 KI270747.1
   4 KI270748.1
   7 KI270749.1
   8 KI270750.1
 256 KI270751.1
  19 KI270753.1
 109 KI270754.1
   1 KI270755.1
   1 KI270756.1
1318 MT
6601 X
 548 Y

===== E3.bam =====
14495 *
8322 1
4224 10
3825 11
3113 12
1687 13
2326 14
2313 15
3470 16
4275 17
1463 18
3683 19
5292 2
2185 20
1591 21
2718 22
4436 3
3200 4
3849 5
3964 6
4284 7
3062 8
3330 9
  10 GL000008.2
  17 GL000009.2
  27 GL000194.1
   6 GL000195.1
  28 GL000205.2
   1 GL000208.1
   1 GL000213.1
 221 GL000214.1
 371 GL000216.2
  11 GL000218.1
   4 GL000219.1
  24 GL000220.1
  12 GL000221.1
  43 GL000224.1
 708 GL000225.1
   1 KI270330.1
   4 KI270438.1
   5 KI270442.1
   2 KI270512.1
   2 KI270519.1
   2 KI270538.1
   2 KI270539.1
   1 KI270579.1
  12 KI270706.1
   5 KI270707.1
   8 KI270708.1
   6 KI270709.1
  12 KI270712.1
   3 KI270713.1
  14 KI270714.1
   4 KI270719.1
  14 KI270721.1
   6 KI270722.1
   7 KI270723.1
  10 KI270724.1
   1 KI270725.1
   1 KI270726.1
   1 KI270727.1
  25 KI270728.1
  12 KI270729.1
  11 KI270731.1
   6 KI270732.1
  24 KI270733.1
  10 KI270734.1
   4 KI270735.1
   5 KI270736.1
   1 KI270737.1
   1 KI270738.1
   2 KI270741.1
   8 KI270742.1
  20 KI270743.1
 456 KI270744.1
   4 KI270745.1
   1 KI270746.1
   5 KI270747.1
   1 KI270748.1
   2 KI270749.1
   1 KI270750.1
 134 KI270751.1
  16 KI270753.1
 108 KI270754.1
   1 KI270756.1
 504 MT
3132 X
 282 Y

In [21]:
# Reads per chromosome

for bam in path.glob("*.bam"):
    print(f"\n===== {bam.name} =====")
    !samtools view {bam} | cut -f3 | sort | uniq -c | sort -k2,2V

===== Rr.bam =====
31886 1
20379 2
17044 3
12096 4
14415 5
14988 6
15019 7
11530 8
11816 9
15794 10
13960 11
11604 12
6848 13
8696 14
8744 15
11687 16
14553 17
5500 18
11934 19
7919 20
5104 21
8762 22
  22 GL000008.2
  38 GL000009.2
  62 GL000194.1
  15 GL000195.1
  60 GL000205.2
   5 GL000208.1
   5 GL000213.1
 682 GL000214.1
1262 GL000216.2
  22 GL000218.1
  20 GL000219.1
 120 GL000220.1
  19 GL000221.1
 114 GL000224.1
2494 GL000225.1
   5 KI270303.1
   7 KI270330.1
   1 KI270435.1
   4 KI270438.1
  47 KI270442.1
   1 KI270467.1
   7 KI270508.1
   5 KI270512.1
   8 KI270519.1
   1 KI270521.1
   6 KI270538.1
   2 KI270581.1
   1 KI270582.1
  29 KI270706.1
   9 KI270707.1
  17 KI270708.1
  25 KI270709.1
   1 KI270710.1
  17 KI270711.1
  36 KI270712.1
  21 KI270713.1
  22 KI270714.1
   1 KI270717.1
  18 KI270719.1
   1 KI270720.1
  29 KI270721.1
  22 KI270722.1
  28 KI270723.1
  28 KI270724.1
   9 KI270725.1
   3 KI270726.1
  16 KI270727.1
  98 KI270728.1
  34 KI270729.1
   2 KI270730.1
  47 KI270731.1
   6 KI270732.1
 111 KI270733.1
  36 KI270734.1
   5 KI270735.1
  17 KI270736.1
   4 KI270737.1
  10 KI270738.1
   2 KI270739.1
   3 KI270741.1
  22 KI270742.1
  50 KI270743.1
1571 KI270744.1
   7 KI270745.1
   2 KI270746.1
  12 KI270747.1
   7 KI270748.1
  14 KI270749.1
  11 KI270750.1
 485 KI270751.1
  35 KI270753.1
 181 KI270754.1
   2 KI270755.1
   1 KI270756.1
   1 KI270757.1
2220 MT
12639 X
 962 Y
97952 *

===== Hs.bam =====
16016 1
10317 2
8619 3
6400 4
7316 5
7511 6
7741 7
5996 8
6093 9
8021 10
6991 11
5847 12
3628 13
4296 14
4415 15
5890 16
6974 17
2765 18
5828 19
4001 20
2512 21
4317 22
  17 GL000008.2
  15 GL000009.2
  25 GL000194.1
  13 GL000195.1
  29 GL000205.2
   2 GL000208.1
   1 GL000213.1
 368 GL000214.1
 765 GL000216.2
  12 GL000218.1
   1 GL000219.1
  66 GL000220.1
  16 GL000221.1
  64 GL000224.1
1509 GL000225.1
   1 KI270310.1
   3 KI270330.1
   1 KI270435.1
   2 KI270438.1
  22 KI270442.1
   1 KI270508.1
   1 KI270512.1
   4 KI270519.1
   4 KI270538.1
   1 KI270539.1
   1 KI270581.1
   1 KI270584.1
  16 KI270706.1
   8 KI270707.1
   8 KI270708.1
  12 KI270709.1
   8 KI270711.1
  18 KI270712.1
   9 KI270713.1
  13 KI270714.1
   2 KI270717.1
   8 KI270719.1
   1 KI270720.1
  20 KI270721.1
   9 KI270722.1
  18 KI270723.1
  18 KI270724.1
   7 KI270725.1
  10 KI270727.1
  44 KI270728.1
  20 KI270729.1
   3 KI270730.1
  17 KI270731.1
   5 KI270732.1
  46 KI270733.1
  19 KI270734.1
   1 KI270735.1
   9 KI270736.1
   1 KI270737.1
   3 KI270738.1
   1 KI270741.1
   8 KI270742.1
  32 KI270743.1
 836 KI270744.1
   3 KI270745.1
   3 KI270746.1
   3 KI270747.1
   4 KI270748.1
   7 KI270749.1
   8 KI270750.1
 256 KI270751.1
  19 KI270753.1
 109 KI270754.1
   1 KI270755.1
   1 KI270756.1
1318 MT
6601 X
 548 Y
40240 *

===== E3.bam =====
8322 1
5292 2
4436 3
3200 4
3849 5
3964 6
4284 7
3062 8
3330 9
4224 10
3825 11
3113 12
1687 13
2326 14
2313 15
3470 16
4275 17
1463 18
3683 19
2185 20
1591 21
2718 22
  10 GL000008.2
  17 GL000009.2
  27 GL000194.1
   6 GL000195.1
  28 GL000205.2
   1 GL000208.1
   1 GL000213.1
 221 GL000214.1
 371 GL000216.2
  11 GL000218.1
   4 GL000219.1
  24 GL000220.1
  12 GL000221.1
  43 GL000224.1
 708 GL000225.1
   1 KI270330.1
   4 KI270438.1
   5 KI270442.1
   2 KI270512.1
   2 KI270519.1
   2 KI270538.1
   2 KI270539.1
   1 KI270579.1
  12 KI270706.1
   5 KI270707.1
   8 KI270708.1
   6 KI270709.1
  12 KI270712.1
   3 KI270713.1
  14 KI270714.1
   4 KI270719.1
  14 KI270721.1
   6 KI270722.1
   7 KI270723.1
  10 KI270724.1
   1 KI270725.1
   1 KI270726.1
   1 KI270727.1
  25 KI270728.1
  12 KI270729.1
  11 KI270731.1
   6 KI270732.1
  24 KI270733.1
  10 KI270734.1
   4 KI270735.1
   5 KI270736.1
   1 KI270737.1
   1 KI270738.1
   2 KI270741.1
   8 KI270742.1
  20 KI270743.1
 456 KI270744.1
   4 KI270745.1
   1 KI270746.1
   5 KI270747.1
   1 KI270748.1
   2 KI270749.1
   1 KI270750.1
 134 KI270751.1
  16 KI270753.1
 108 KI270754.1
   1 KI270756.1
 504 MT
3132 X
 282 Y
14495 *

In [7]:
# Summary table

import pandas as pd
import subprocess

results = []

for bam in path.glob("*.bam"):
    total = int(subprocess.check_output(
        f"samtools view -c {bam}", shell=True
    ).decode().strip())

    unique = int(subprocess.check_output(
        f"samtools view -q 30 -c {bam}", shell=True
    ).decode().strip())

    multi = int(subprocess.check_output(
        f"samtools view -c -f 256 {bam}", shell=True
    ).decode().strip())

    results.append({
        "sample": bam.name,
        "total_reads": total,
        "unique_MAPQ30": unique,
        "secondary_alignments": multi
    })

df = pd.DataFrame(results)
df

   sample  total_reads  unique_MAPQ30  secondary_alignments
0  Rr.bam       402194         241252                     0
1  Hs.bam       194790         123045                     0
2  E3.bam        97490          66326                     0

## BWA alignment against a1_E3 vector (filtered reads containing CMV primer sequence)

In [1]:
# -- Create directories for references/aligments (RUN JUST ONCE)
from pathlib import Path

# -- Create directories for references/alignments
path = Path('/Users/leandro/Desktop/github/NGS-data/ORF2library1_260411/alignments/BWA/over-a1E3')

In [4]:
# Basic mapping statistics

for bam in path.glob("*.bam"):
    print(f"\n===== {bam.name} =====")
    !samtools flagstat {bam}

===== Rr.bam =====
382742 + 0 in total (QC-passed reads + QC-failed reads)
382203 + 0 primary
0 + 0 secondary
539 + 0 supplementary
0 + 0 duplicates
0 + 0 primary duplicates
382742 + 0 mapped (100.00% : N/A)
382203 + 0 primary mapped (100.00% : N/A)
0 + 0 paired in sequencing
0 + 0 read1
0 + 0 read2
0 + 0 properly paired (N/A : N/A)
0 + 0 with itself and mate mapped
0 + 0 singletons (N/A : N/A)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)

===== Hs.bam =====
185381 + 0 in total (QC-passed reads + QC-failed reads)
185114 + 0 primary
0 + 0 secondary
267 + 0 supplementary
0 + 0 duplicates
0 + 0 primary duplicates
185381 + 0 mapped (100.00% : N/A)
185114 + 0 primary mapped (100.00% : N/A)
0 + 0 paired in sequencing
0 + 0 read1
0 + 0 read2
0 + 0 properly paired (N/A : N/A)
0 + 0 with itself and mate mapped
0 + 0 singletons (N/A : N/A)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)

===== E3.bam =====
92810 + 0 in total (QC-passed reads + QC-failed reads)
92673 + 0 primary
0 + 0 secondary
137 + 0 supplementary
0 + 0 duplicates
0 + 0 primary duplicates
92810 + 0 mapped (100.00% : N/A)
92673 + 0 primary mapped (100.00% : N/A)
0 + 0 paired in sequencing
0 + 0 read1
0 + 0 read2
0 + 0 properly paired (N/A : N/A)
0 + 0 with itself and mate mapped
0 + 0 singletons (N/A : N/A)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)

In [2]:
# Number of distinct genomic loci hit

import subprocess

for bam in path.glob("*.bam"):
    print(f"\n===== {bam.name} =====")
    cmd = f"samtools view {bam} | awk '{{print $3\":\"$4}}' | sort | uniq | wc -l"
    subprocess.run(cmd, shell=True)

===== Rr.bam =====
      64

===== Hs.bam =====
      50

===== E3.bam =====
      61

In [16]:
# Reads per chromosome

for bam in path.glob("*.bam"):
    print(f"\n===== {bam.name} =====")
    !samtools view {bam} | cut -f3 | sort | uniq -c

===== Rr.bam =====
382742 a1_E3

===== Hs.bam =====
185381 a1_E3

===== E3.bam =====
92810 a1_E3

In [3]:
# Summary table

import pandas as pd
import subprocess

results = []

for bam in path.glob("*.bam"):
    total = int(subprocess.check_output(
        f"samtools view -c {bam}", shell=True
    ).decode().strip())

    unique = int(subprocess.check_output(
        f"samtools view -q 30 -c {bam}", shell=True
    ).decode().strip())

    multi = int(subprocess.check_output(
        f"samtools view -c -f 256 {bam}", shell=True
    ).decode().strip())

    results.append({
        "sample": bam.name,
        "total_reads": total,
        "unique_MAPQ30": unique,
        "secondary_alignments": multi
    })

df = pd.DataFrame(results)
df

   sample  total_reads  unique_MAPQ30  secondary_alignments
0  Rr.bam       382742            431                     0
1  Hs.bam       185381            226                     0
2  E3.bam        92810            119                     0